apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    commit: 9c8695ac6df672cd9444ca06da4debe138f1c7d2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        commit: 9c8695ac6df672cd9444ca06da4debe138f1c7d2
        color: green
    spec:
      containers:
      - name: hello-world
        image: iad.ocir.io/orasenatdpltdevopsnetw01/helloworldtest/helloworld:master-9c8695ac6df672cd9444ca06da4debe138f1c7d2
        imagePullPolicy: Always
        ports:
        - name: hello-world
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: podinfo
            mountPath: /tmp
            readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
    commit: 9c8695ac6df672cd9444ca06da4debe138f1c7d2
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: hello-world
    color: green
  type: ClusterIP
---
